package manifest

import (
	"errors"
	"pgregory.net/rapid"
	"strings"
	"testing"
	"time"
)

// testHelper is the small interface satisfied by both *testing.T and
// *rapid.T, so the same helpers can be reused across L2 examples and
// L1 rapid properties (dark-testing §5.3 pattern).
type testHelper interface {
	Helper()
	Fatalf(format string, args ...any)
}

// rapidScope returns a randomly generated scope string that is guaranteed
// to satisfy IsValidScopeName. Used by properties that need valid scopes.
func rapidScope() *rapid.Generator[string] {
	return rapid.Custom[string](func(t *rapid.T) string {
		resource := rapid.SampledFrom([]string{"manifest", "drift", "agent_memory", "research", "session", "audit", "update"}).Draw(t, "resource")
		action := rapid.SampledFrom([]string{"read", "write", "resolve", "grant", "revoke", "list", "execute"}).Draw(t, "action")
		return resource + ":" + action
	})
}

// rapidValidToken returns a randomly generated but well-formed CapToken.
// Used as the starting point for properties that mutate one field at a time.
func rapidValidToken() *rapid.Generator[*CapToken] {
	return rapid.Custom[*CapToken](func(t *rapid.T) *CapToken {
		month := time.Month(1 + rapid.IntRange(0, 11).Draw(t, "month"))
		now := time.Date(2026, month, 1, 12, 0, 0, 0, time.UTC)
		scopeCount := rapid.IntRange(1, 5).Draw(t, "scopeCount")
		scopes := make([]string, scopeCount)
		for i := 0; i < scopeCount; i++ {
			scopes[i] = rapidScope().Draw(t, "scope")
		}
		ttlHours := rapid.IntRange(1, 168).Draw(t, "ttlHours")
		return &CapToken{
			ID:        "cap-" + rapid.StringMatching(`[a-z0-9]{8}`).Draw(t, "id"),
			Operator:  "operator-" + rapid.StringMatching(`[a-z0-9]{4}`).Draw(t, "operator"),
			Scopes:    scopes,
			GrantedAt: now,
			ExpiresAt: now.Add(time.Duration(ttlHours) * time.Hour),
			Signature: []byte(rapid.StringMatching(`.{32,128}`).Draw(t, "sig")),
			SignedBy:  "admin-" + rapid.StringMatching(`[a-z0-9]{4}`).Draw(t, "signedBy"),
		}
	})
}

// Property: HasScope is true iff the queried scope appears in the token's
// Scopes slice. This catches the "off-by-one / linear-scan bug" class
// (e.g. forgetting to iterate, wrong comparison operator).
func TestProperty_CapToken_HasScopeExactlyMatchesScopes(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		tok := rapidValidToken().Draw(rt, "tok")
		// Pick a scope from the token's own Scopes — must return true.
		present := rapid.SampledFrom(tok.Scopes).Draw(rt, "present")
		if !tok.HasScope(present) {
			rt.Fatalf("HasScope(%q): expected true (scope IS in Scopes=%v)", present, tok.Scopes)
		}
		// Pick a scope guaranteed not in Scopes — must return false.
		// Generate candidates and find one not present.
		absent := ""
		for i := 0; i < 20; i++ {
			candidate := rapidScope().Draw(rt, "candidate")
			found := false
			for _, s := range tok.Scopes {
				if s == candidate {
					found = true
					break
				}
			}
			if !found {
				absent = candidate
				break
			}
		}
		if absent == "" {
			rt.Skip("could not find absent scope (very dense Scopes)")
		}
		if tok.HasScope(absent) {
			rt.Fatalf("HasScope(%q): expected false (scope NOT in Scopes=%v)", absent, tok.Scopes)
		}
	})
}

// Property: a well-formed token generated by rapidValidToken always passes
// Validate. Catches regressions where a new invariant makes previously
// valid tokens fail (e.g. tightening IsValidScopeName rules).
func TestProperty_CapToken_ValidTokenAlwaysValidates(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		tok := rapidValidToken().Draw(rt, "tok")
		if err := tok.Validate(); err != nil {
			rt.Fatalf("Validate on rapid-valid token: got error %v (token=%+v)", err, tok)
		}
	})
}

// Property: IsActive at GrantedAt is always true (the start of the window
// is inclusive), and IsActive at ExpiresAt is always false (the end is
// exclusive). Catches regressions where the boundary semantics flip.
func TestProperty_CapToken_IsActiveBoundarySemantics(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		tok := rapidValidToken().Draw(rt, "tok")
		// RevokedAt is the zero value in rapidValidToken, so not revoked.
		if !tok.IsActive(tok.GrantedAt) {
			rt.Fatalf("IsActive at GrantedAt: expected true (inclusive start)")
		}
		if tok.IsActive(tok.ExpiresAt) {
			rt.Fatalf("IsActive at ExpiresAt: expected false (exclusive end)")
		}
	})
}

// Property: revocation makes IsActive false at and after RevokedAt, even
// if ExpiresAt is in the future. Catches the "revocation ignored" bug.
func TestProperty_CapToken_RevocationTakesPrecedence(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		tok := rapidValidToken().Draw(rt, "tok")
		// Insert a RevokedAt between GrantedAt and ExpiresAt.
		delta := tok.ExpiresAt.Sub(tok.GrantedAt)
		tok.RevokedAt = tok.GrantedAt.Add(delta / 2)

		if tok.IsActive(tok.RevokedAt) {
			rt.Fatalf("IsActive at RevokedAt: expected false")
		}
		if tok.IsActive(tok.RevokedAt.Add(time.Second)) {
			rt.Fatalf("IsActive after RevokedAt: expected false")
		}
		// Before RevokedAt should still be active.
		if !tok.IsActive(tok.GrantedAt) {
			rt.Fatalf("IsActive at GrantedAt (before revoke): expected true")
		}
	})
}

// Property: clearing Scopes (setting to nil) makes Validate fail with
// ErrEmptyCapScopes. Catches regressions where Scopes=nil is accepted.
func TestProperty_CapToken_EmptyScopesAlwaysRejected(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		tok := rapidValidToken().Draw(rt, "tok")
		tok.Scopes = nil
		err := tok.Validate()
		if !errors.Is(err, ErrEmptyCapScopes) {
			rt.Fatalf("Validate with nil Scopes: expected ErrEmptyCapScopes, got %v", err)
		}
	})
}

// Property: ExpiresAt <= GrantedAt always fails Validate with
// ErrBadCapExpiry. Catches regressions where equal-time becomes valid.
func TestProperty_CapToken_InvertedExpiryAlwaysRejected(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		tok := rapidValidToken().Draw(rt, "tok")
		tok.ExpiresAt = tok.GrantedAt
		if !errors.Is(tok.Validate(), ErrBadCapExpiry) {
			rt.Fatalf("Validate with equal expiry: expected ErrBadCapExpiry")
		}
		tok.ExpiresAt = tok.GrantedAt.Add(-1 * time.Hour)
		if !errors.Is(tok.Validate(), ErrBadCapExpiry) {
			rt.Fatalf("Validate with inverted expiry: expected ErrBadCapExpiry")
		}
	})
}

// Property: IsValidScopeName is a stable predicate — calling it twice on
// the same input yields the same result. Catches non-determinism (e.g.
// from a broken regex or map iteration).
func TestProperty_IsValidScopeName_Deterministic(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		s := rapid.String().Draw(rt, "scope")
		first := IsValidScopeName(s)
		second := IsValidScopeName(s)
		if first != second {
			rt.Fatalf("IsValidScopeName non-deterministic for %q: first=%v second=%v", s, first, second)
		}
	})
}

// Property: IsValidScopeName accepts exactly the strings of the form
// "resource:action" where both halves are lowercase [a-z0-9_]+ and each
// half is 1-32 chars. Random strings that don't match get rejected.
func TestProperty_IsValidScopeName_RejectsAllMalformed(t *testing.T) {
	rapid.Check(t, func(rt *rapid.T) {
		s := rapid.String().Draw(rt, "scope")
		// Skip the property if s happens to be valid — properties
		// should focus on the malformed case.
		if IsValidScopeName(s) {
			return
		}
		// Verify the rejection is for a real reason:
		// either length, missing colon, multiple colons, uppercase, or bad chars.
		hasUpper := false
		for _, r := range s {
			if r >= 'A' && r <= 'Z' {
				hasUpper = true
				break
			}
		}
		hasMultipleColon := strings.Count(s, ":") > 1
		noColon := !strings.Contains(s, ":")
		tooLong := len(s) > 66
		tooShort := len(s) < 3
		if !hasUpper && !hasMultipleColon && !noColon && !tooLong && !tooShort {
			// Some other reason for rejection — log it. This isn't a
			// failure, just a coverage check.
			t.Logf("rejected %q for non-obvious reason", s)
		}
	})
}
